"""add match scores

Revision ID: 04d25b6ba7d6
Revises: b5927c7f988b
Create Date: 2026-08-28 22:18:01.892356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04d25b6ba7d6'
down_revision: Union[str, Sequence[str], None] = 'b5927c7f988b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('team1_score', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('team2_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'team2_score')
    op.drop_column('matches', 'team1_score')
    # ### end Alembic commands ###
