"""add map and player stats tables

Revision ID: e1e559704e17
Revises: 04d25b6ba7d6
Create Date: 2026-08-29 14:54:49.250751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1e559704e17'
down_revision: Union[str, Sequence[str], None] = '04d25b6ba7d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vlr_game_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('map_number', sa.Integer(), nullable=False),
    sa.Column('map_name', sa.String(length=50), nullable=False),
    sa.Column('team1_score', sa.Integer(), nullable=True),
    sa.Column('team2_score', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vlr_game_id')
    )
    op.create_table('player_map_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_map_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('agents', sa.String(length=100), nullable=True),
    sa.Column('rating_all', sa.Float(), nullable=True),
    sa.Column('rating_attack', sa.Float(), nullable=True),
    sa.Column('rating_defense', sa.Float(), nullable=True),
    sa.Column('acs_all', sa.Integer(), nullable=True),
    sa.Column('acs_attack', sa.Integer(), nullable=True),
    sa.Column('acs_defense', sa.Integer(), nullable=True),
    sa.Column('kills_all', sa.Integer(), nullable=True),
    sa.Column('kills_attack', sa.Integer(), nullable=True),
    sa.Column('kills_defense', sa.Integer(), nullable=True),
    sa.Column('deaths_all', sa.Integer(), nullable=True),
    sa.Column('deaths_attack', sa.Integer(), nullable=True),
    sa.Column('deaths_defense', sa.Integer(), nullable=True),
    sa.Column('assists_all', sa.Integer(), nullable=True),
    sa.Column('assists_attack', sa.Integer(), nullable=True),
    sa.Column('assists_defense', sa.Integer(), nullable=True),
    sa.Column('kill_diff_all', sa.Integer(), nullable=True),
    sa.Column('kill_diff_attack', sa.Integer(), nullable=True),
    sa.Column('kill_diff_defense', sa.Integer(), nullable=True),
    sa.Column('kast_all', sa.Float(), nullable=True),
    sa.Column('kast_attack', sa.Float(), nullable=True),
    sa.Column('kast_defense', sa.Float(), nullable=True),
    sa.Column('adr_all', sa.Float(), nullable=True),
    sa.Column('adr_attack', sa.Float(), nullable=True),
    sa.Column('adr_defense', sa.Float(), nullable=True),
    sa.Column('hs_pct_all', sa.Float(), nullable=True),
    sa.Column('hs_pct_attack', sa.Float(), nullable=True),
    sa.Column('hs_pct_defense', sa.Float(), nullable=True),
    sa.Column('first_kills_all', sa.Integer(), nullable=True),
    sa.Column('first_kills_attack', sa.Integer(), nullable=True),
    sa.Column('first_kills_defense', sa.Integer(), nullable=True),
    sa.Column('first_deaths_all', sa.Integer(), nullable=True),
    sa.Column('first_deaths_attack', sa.Integer(), nullable=True),
    sa.Column('first_deaths_defense', sa.Integer(), nullable=True),
    sa.Column('first_kill_diff_all', sa.Integer(), nullable=True),
    sa.Column('first_kill_diff_attack', sa.Integer(), nullable=True),
    sa.Column('first_kill_diff_defense', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_map_id'], ['match_maps.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_map_id', 'player_id', name='uq_player_map_stats_map_player')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_map_stats')
    op.drop_table('match_maps')
    # ### end Alembic commands ###
