"""add forecasts table

Revision ID: eaf7597a5438
Revises: e1e559704e17
Create Date: 2026-09-01 12:16:24.174033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaf7597a5438'
down_revision: Union[str, Sequence[str], None] = 'e1e559704e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team1_id', sa.Integer(), nullable=False),
    sa.Column('team2_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_key', sa.String(length=150), nullable=False),
    sa.Column('team1_win_probability', sa.Float(), nullable=False),
    sa.Column('rationale', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lock_time', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source_type IN ('human', 'model', 'market')", name='ck_forecasts_source_type'),
    sa.CheckConstraint('created_at < lock_time', name='ck_forecasts_before_lock'),
    sa.CheckConstraint('team1_id <> team2_id', name='ck_forecasts_different_teams'),
    sa.CheckConstraint('team1_win_probability >= 0.0 AND team1_win_probability <= 1.0', name='ck_forecasts_probability'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['team1_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team2_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'source_key', name='uq_forecasts_match_source')
    )
    op.create_index(op.f('ix_forecasts_match_id'), 'forecasts', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecasts_match_id'), table_name='forecasts')
    op.drop_table('forecasts')
    # ### end Alembic commands ###
